Support rateLimitPerUser for every Guild Message Channel type
Discord4J/Discord4J pull request #1154
Opened 2023-06-11 15:02 UTC by Doc94

**Description:** Based in a previous issue all guild channel with messages allow set a rate limit per user in messages send, this currently in code are only for normal messages, things like news channel or voice channel dont allow this, this PR allow get the value and also set also update the docs to reflect the new max value allowed by docs.

**Justification:** This close https://github.com/Discord4J/Discord4J/issues/1111

**Note:** the structure of channel classes is a little mess for me.. then i hope move the method to the correct place.

2023-06-11 17:48 UTC, quanticc requested changes
Looks like we need to point this one to 3.3.0, because moving a method upwards in the class hierarchy would break compatibility.

The channel hierarchy changes there, so I believe the method should be moved to [`TopLevelGuildMessageChannel`](https://github.com/Discord4J/Discord4J/blob/3aa15d1f45630d8c8cc580d835b5f8a0a13083f8/core/src/main/java/discord4j/core/object/entity/channel/TopLevelGuildMessageChannel.java) as a default method

2023-06-11 19:26 UTC, Doc94 commented
> Looks like we need to point this one to 3.3.0, because moving a method upwards in the class hierarchy would break compatibility.
> 
> The channel hierarchy changes there, so I believe the method should be moved to [`TopLevelGuildMessageChannel`](https://github.com/Discord4J/Discord4J/blob/3aa15d1f45630d8c8cc580d835b5f8a0a13083f8/core/src/main/java/discord4j/core/object/entity/channel/TopLevelGuildMessageChannel.java) as a default method

then you mean rebase all this from master and only add the method in [TopLevelGuildMessageChannel](https://github.com/Discord4J/Discord4J/blob/3aa15d1f45630d8c8cc580d835b5f8a0a13083f8/core/src/main/java/discord4j/core/object/entity/channel/TopLevelGuildMessageChannel.java)? the only thing with this is how is subject to the snapshots of 3.3.x :/

2023-06-11 19:57 UTC, quanticc commented
Yep, moving the method to that class, keeping the Create/Edit specs you modified and master should be the base branch

2023-06-11 20:44 UTC, Doc94 commented
> Yep, moving the method to that class, keeping the Create/Edit specs you modified and master should be the base branch

Ready and also include Stage channels because allow this value to.

2023-06-12 01:14 UTC, quanticc commented
> Ready and also include Stage channels because allow this value to.

Right, so to include Stage, looks like the right place is `CategorizableChannel` - meaning it would apply to: Text, Voice, Stage, News and Forum

Do we also have to include it in ThreadChannel? It would have to be added separately

2023-06-12 03:27 UTC, quanticc approved these changes

2023-06-12 03:28 UTC, merged