feat: add support for monetization endpoints, skus and entitlements
Discord4J/Discord4J pull request #1184
Opened 2024-03-18 18:36 UTC by Azn9

**Description:** add support for monetization endpoints, skus and entitlements

https://discord.com/developers/docs/monetization/overview
Requires https://github.com/Discord4J/discord-json/pull/160

2024-03-19 02:25 UTC, Azn9 commented on rest/src/main/java/discord4j/rest/service/MonetizationService.java
> +    public Flux<EntitlementData> getAllEntitlements(long applicationId) {
Add support for all query params (https://discord.com/developers/docs/monetization/entitlements#list-entitlements-query-params)

2024-05-19 03:08 UTC, Doc94 requested changes

2024-05-19 03:08 UTC, Doc94 commented on core/src/main/java/discord4j/core/object/monetization/SKU.java
> +    public enum Type {
Missing DURABLE and CONSUMABLE type
ref: https://discord.com/developers/docs/monetization/skus#sku-object-sku-types

2024-07-17 19:53 UTC, Doc94 approved these changes

2024-07-17 20:39 UTC, merged