Support for the Guild Resource Navigation
Discord4J/Discord4J pull request #1197
Opened 2024-03-29 14:45 UTC by Doc94

**Description:** Close #1194 adding a utility enum for the resource navigation.

**Justification:** https://discord.com/developers/docs/reference#message-formatting-guild-navigation-types

2024-05-12 21:58 UTC, Azn9 requested changes
Aren't you missing the getResourceNavigationChannelTag (or something like that) method?

2024-05-12 22:02 UTC, Doc94 commented
> Aren't you missing the getResourceNavigationChannelTag (or something like that) method?

In where?
This class is more a helper enum for call the getMention

2024-05-18 15:42 UTC, Azn9 approved these changes

2024-05-18 16:22 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/entity/Guild.java
> +            return "<id:" + this.value  + ">";
```suggestion
            return "<%d:" + this.value  + ">";
```

2024-05-18 16:22 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/entity/Guild.java
> +        return String.format(resourceNavigation.getMention(), data.id().asString());
```suggestion
        return String.format(resourceNavigation.getMention(), data.id().asLong());
```

2024-05-19 14:07 UTC, merged