Rework Emoji object for general purpose
Discord4J/Discord4J pull request #1262
Opened 2024-08-11 20:56 UTC by Doc94

**Description:** This PR rename the ReactionEmoji to Emoji for reflects the general purpuse currently in that class also thanks to https://github.com/Discord4J/Discord4J/commit/b682ed80543515a9b73ec4de893909344d20a139 this PR reduce the redundancy of the possible two Emoji classes this is heavy breaking change because rename and move all for more consistency.

**Justification:** When the ReactionEmoji start was supposed to just a reaction helper class with the time this class start to be used for another things and with the Components release the "Reaction" its just confusing for new users.

2025-04-25 22:40 UTC, Azn9 requested changes
Not a lot of changes, only a few details

2025-04-25 22:40 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/emoji/EmojiCustom.java
> +public class EmojiCustom extends Emoji {
"CustomEmoji" would be better

2025-04-25 22:40 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/emoji/EmojiCustom.java
> +    public EmojiCustom(EmojiData data) {
Why change the access?

2025-04-25 22:40 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/emoji/EmojiUnicode.java
> +public class EmojiUnicode extends Emoji {
Same, "UnicodeEmoji"

2025-04-25 22:40 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/emoji/EmojiUnicode.java
> +public class EmojiUnicode extends Emoji {
And add a few comments maybe?

2025-04-25 22:40 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/emoji/EmojiUnicode.java
> +        return "ReactionEmoji.Unicode{" +
Not updated

2025-04-25 22:40 UTC, Azn9 commented on core/src/main/java/discord4j/core/object/entity/ApplicationEmoji.java
> +public final class ApplicationEmoji extends EmojiCustom implements Entity {
Needs to update the javadoc

2025-04-25 22:45 UTC, Doc94 commented on core/src/main/java/discord4j/core/object/emoji/EmojiCustom.java
> +    public EmojiCustom(EmojiData data) {
If remember the idea was make a simple way to get this class and move the gateway to the GuildEmoji or ApplicationEmoji

2025-04-26 00:52 UTC, Doc94 commented on core/src/main/java/discord4j/core/object/emoji/EmojiCustom.java
> +    public EmojiCustom(EmojiData data) {
This also allow parse the Data and use the basic methods outside of the Gateway requirement moved to Guild/Application

2025-04-29 16:29 UTC, merged