Update README.md
Discord4J/Discord4J pull request #1292
Opened 2024-11-23 01:07 UTC by HighHowDoIPlay

Added info about my bot in the "Large Bots" section

**Description:** 

**Justification:**

2024-11-26 02:24 UTC, Doc94 requested changes
Hi,
Can you point this to 3.2.x? (for make the changes in the two current branches)

2024-11-26 02:24 UTC, Doc94 commented on README.md
> +* [See-Bot](https://seebot.dev) - A Fortnite focused bot with stat tracking, player lookup, mission alerts, and much more, in over 10k servers
```suggestion
* [See-Bot](https://seebot.dev) - A Fortnite focused bot with stat tracking, player lookup, mission alerts, and much more; in over 10k servers.
```

2024-12-02 13:32 UTC, HighHowDoIPlay commented
> Hi, Can you point this to 3.2.x? (for make the changes in the two current branches)

Believe I did, not sure if I did it right.

2024-12-08 12:59 UTC, Doc94 commented
> > Hi, Can you point this to 3.2.x? (for make the changes in the two current branches)
> 
> Believe I did, not sure if I did it right.

Thanks, yeah the just change cause a masive list of commits added. i get into the branch and make a few changes for clean this.

2024-12-08 12:59 UTC, merged