New specs
Discord4J/Discord4J pull request #750
Opened 2020-07-31 01:11 UTC by darichey

**Description:**
Initial work on new specs.

I've done a few already, if you want to help, make sure to follow the pattern. Feedback appreciated. Specifically, I'm not necessarily satisfied with the attempt at abstraction/code sharing in `ConfigurableRequest` and `AuditableRequest`. I couldn't get the hierarchy to work well for things like `BanMono` which don't have internal builders. However, there are very few of these kinds of requests and it should be impossible for an outside user to trigger an error.

**Justification:**
Closes #693

2020-09-26 17:30 UTC, quanticc requested changes

2020-09-26 17:30 UTC, quanticc commented on core/src/main/java/discord4j/core/spec/GuildMemberEditMono.java
> +    Mono<Void> getRequest() {
In v8 this route returns MemberData

2020-10-26 04:35 UTC, quanticc commented
Now I think we'll need to re-add the old Spec based methods. Deprecate them during 3.2 and removal should happen on 3.3

2020-11-16 02:42 UTC, quanticc commented
@darichey I'm looking forward to merging this + #764 but maintaining old spec methods to provide a smoother migration path. What do you think?

2021-03-26 21:16 UTC, darichey commented
Unfortunately, after a final push to get this done, I think I may have discovered something that could require rethinking our approach here. Consider the following method https://github.com/Discord4J/Discord4J/blob/884e0af6dd2e968dc3a576197103e4afe55d120a/core/src/test/java/discord4j/core/command/CommandOperations.java#L99-L105
How would this method be written with the proposed `MessageCreateMono`? I'm not sure it's possible. This was surprisingly the only method in our own codebase that does something like this, but I think it's a warning that this approach might not be all we thought it was.

Both this and the old approach take a kind of "ephemeral" approach to configuring actions. There is no concrete, tangible configuration data that can be manipulated like many people expect. Further, I think that's part of what leads to difficulty/confusion with the old design, and I'm not confident that this new design addresses that. Moreover, we may be further restricting the kinds of programs that can be written (assuming we cannot write the method above).

2021-03-27 14:46 UTC, quanticc commented
I think it comes down whether we want to keep both approaches for v3.3. The example you quoted would have to use the current `createMessage(Consumer<? super MessageCreateSpec> spec)` right now, but it can be adapted if we accept externally configurable object to something like `fromSpec(...)` in this new PR.

2021-04-02 18:41 UTC, darichey commented
I think ultimately this approach is going to cause problems. Unfortunately, I'm going to close this PR (we can keep the branch for a bit), and let's go back to immutable specs in #585.

2021-04-02 18:41 UTC, closed without merging