Add methods for obtaining an existing, registered VoiceConnection to associated entities
Discord4J/Discord4J pull request #783
Opened 2020-09-27 17:29 UTC by cameronprater

**Description:** Adds method to obtain a VoiceConnection registered to a guild snowflake through VoiceConnectionRegistry directly to Guild. Also adds a method to obtain a registered VoiceConnection from a VoiceChannel.

**Justification:** https://discordapp.com/channels/208023865127862272/451125724766535710/758786914496151562

2020-09-30 14:06 UTC, darichey requested changes
Thanks, we need more utilities like this. Just some wording changes in the javadoc.

@quanticc Do we need to do anything special here considering that `VoiceConnectionRegistry` is `@Experimental`?

2020-09-30 14:06 UTC, darichey commented on core/src/main/java/discord4j/core/object/entity/Guild.java
> +     * Requests to retrieve the voice connection that the client is propagating in this guild.
I think we don't need to use the wording "requests to retrieve" here. Maybe just modify the summary from `VoiceConnectionRegistry#getVoiceConnection(Snowflake)`.

2020-09-30 14:06 UTC, darichey commented on core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java
> +     * Requests to retrieve the voice connection that the client is propagating in this voice channel.
Same here.

2020-09-30 14:06 UTC, darichey commented on core/src/main/java/discord4j/core/object/entity/Guild.java
> +     * @return A {@link Mono} that emits the voice connection that the client is propagating in this guild, if present,
Same here, just copy from `getVoiceConnection`

2020-09-30 14:06 UTC, darichey commented on core/src/main/java/discord4j/core/object/entity/channel/VoiceChannel.java
> +     * @return A {@link Mono} that emits the voice connection associated with this voice channel, if present and if
And here, further specifying that it might be empty if the voice connection is associated to a different channel in this guild.

2020-09-30 21:23 UTC, quanticc commented
> @quanticc Do we need to do anything special here considering that `VoiceConnectionRegistry` is `@Experimental`?

Not really. the public API is marked as experimental as we gain confidence it's the right solution

2020-10-04 21:24 UTC, cameronprater commented
I updated the documentation as I interpreted your requested changes, but if there's anything still incorrect about the wording, feel free to let me know ^^

2020-10-04 23:21 UTC, darichey approved these changes
LGTM

2020-10-05 03:32 UTC, merged