Remove USER_DMS_GET
Discord4J/Discord4J pull request #890
Opened 2021-04-07 10:08 UTC by Shadorc

**Description:** Removes `USER_DMS_GET` route. This endpoint returns an empty list and is now useless.

**Justification:** https://github.com/discord/discord-api-docs/pull/2770/files

2021-04-10 04:57 UTC, darichey approved these changes

2021-04-10 16:20 UTC, quanticc requested changes
Please deprecate this instead, keep the test removed, and we'll remove it when merging into master

2021-04-10 19:28 UTC, Shadorc commented
Fixed

2021-04-11 04:15 UTC, quanticc approved these changes

2021-04-11 04:17 UTC, merged