Implements discord-json changes
Discord4J/Discord4J pull request #895
Opened 2021-04-10 22:16 UTC by Shadorc

**Description:** Implements discord-json changes.

**Justification:** #894

2021-04-13 00:58 UTC, quanticc requested changes
Thanks a lot for keeping the project up to date with discord changes. I would like to merge this with rebase or fast-forward to keep commits local to a discord-json ticket and to make merging to 3.2.x simpler.

For that I have one request: Any chance we can get an update to each commit messages (via interactive rebase) to correctly refer to the ticket they cover? Now they point to a very old Discord4J issue instead of a discord-json issue.

2021-04-13 00:58 UTC, quanticc commented on core/src/main/java/discord4j/core/event/domain/integration/IntegrationCreateEvent.java
> +package discord4j.core.event.domain.integration;
Missing license header

2021-04-13 00:58 UTC, quanticc commented on core/src/main/java/discord4j/core/event/domain/integration/IntegrationDeleteEvent.java
> +package discord4j.core.event.domain.integration;
Missing license header

2021-04-13 00:58 UTC, quanticc commented on core/src/main/java/discord4j/core/event/domain/integration/IntegrationUpdateEvent.java
> +package discord4j.core.event.domain.integration;
Missing license header

2021-04-13 00:58 UTC, quanticc commented on core/src/main/java/discord4j/core/object/entity/Integration.java
> +package discord4j.core.object.entity;
Missing license header

2021-04-13 09:14 UTC, Shadorc commented
Is it better now?

2021-04-13 17:20 UTC, quanticc reviewed
Awesome, thanks

2021-04-13 17:20 UTC, quanticc approved these changes

2021-04-13 22:26 UTC, darichey commented
Should we take care of the couple TODOs before merging?

- I can't think of a use case for cached integrations
- I think the getters for Integration properties should be fairly straightforward

2021-04-13 23:39 UTC, Shadorc commented
TODO have been adressed!

2021-04-14 00:11 UTC, darichey approved these changes

2021-04-14 02:35 UTC, merged