Add support for banner and bannerAccentColor
Discord4J/Discord4J pull request #977
Opened 2021-07-29 18:35 UTC by Azn9

**Description:** Add methods User#getBannerUrl(ImageFormat) and User#getBannerAccentColor()

**Justification:** 
Closes #965 
Require https://github.com/Discord4J/discord-json/pull/103

2021-08-08 23:29 UTC, quanticc commented
on hold until discord docs issue is merged

2021-08-19 02:47 UTC, darichey requested changes
Great start! Just a couple of things:
* We can use `Possible.flatOpt()` to flatten the `Possible<Optional<T>>` to `Optional<T>` more nicely
* Let's convert the integer to a `Color` for convenience and consistency 
* Let's also add a `getBanner(Image.Format)` that can look exactly like `getAvatar`, again for convenience and consistency

2021-08-19 02:47 UTC, darichey commented on core/src/main/java/discord4j/core/object/entity/User.java
> +                String.format(BANNER_IMAGE_PATH, getId().asString(), avatar), format));
```suggestion
        return Possible.flatOpt(data.banner()).map(avatar -> ImageUtil.getUrl(
                String.format(BANNER_IMAGE_PATH, getId().asString(), avatar), format));
```

2021-08-19 02:47 UTC, darichey commented on core/src/main/java/discord4j/core/object/entity/User.java
> +    }
```suggestion
    public final Optional<Color> getAccentColor() {
        return Possible.flatOpt(data.accentColor())
                .map(Color::of);
    }
```

2021-08-19 19:31 UTC, darichey approved these changes
Looks great, thanks!

2021-08-20 03:52 UTC, merged